In [4]:
import numpy as np
import pandas as pd

In [5]:
credits = pd.read_csv('tmdb_5000_credits.csv')
movies = pd.read_csv('tmdb_5000_movies.csv')

In [6]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [7]:
movies.shape

(4803, 20)

In [8]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [9]:
movies = movies.merge(credits,on='title')

In [10]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [11]:
#genre
#id to make posters
#keywords
#title
#overview
#cast
#crew

movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [12]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [13]:
import ast

In [14]:
def convert(text):
    L = []
    for i in ast.literal_eval(text):
        L.append(i['name']) 
    return L

In [15]:
movies.dropna(inplace=True)

In [16]:
movies['genres'] = movies['genres'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [17]:
movies['keywords'] = movies['keywords'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [18]:
import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [19]:
def convert3(text):
    L = []
    counter = 0
    for i in ast.literal_eval(text):
        if counter < 3:
            L.append(i['name'])
        counter+=1
    return L

In [20]:
movies['cast'] = movies['cast'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [21]:
movies['cast'] = movies['cast'].apply(lambda x:x[0:3])

In [22]:
def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L

In [23]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [24]:
#movies['overview'] = movies['overview'].apply(lambda x:x.split())
movies.sample(5)

,movie_id,title,overview,genres,keywords,cast,crew
2951,11109,Vera Drake,Abortionist Vera Drake finds her beliefs and p...,"[Crime, Drama]","[england, mother role, women's prison, police,...","[Imelda Staunton, Sally Hawkins, Richard Graham]",[Mike Leigh]
1356,9776,Head of State,When a presidential candidate dies unexpectedl...,[Comedy],"[usa, black people, usa president, presidentia...","[Chris Rock, Bernie Mac, Dylan Baker]",[Chris Rock]
4490,26837,B-Girl,"A young female breakdancer, Angel, moves to Lo...","[Crime, Drama, Music]","[dancing, hip-hop, b-girl, street dance, b-boy...","[Julie 'Jules' Urich, Missy Yager, Wesley Jona...",[Emily Dell]
4135,13075,Sherrybaby,"After serving time in prison, former drug addi...",[Drama],"[independent film, mother daughter relationshi...","[Maggie Gyllenhaal, Michelle Hurst, Sandra Rod...",[Laurie Collyer]
3507,9282,11:14,Tells the seemingly random yet vitally connect...,"[Crime, Drama, Thriller]","[alcohol, sex, robbery, secret, gun, ambulance...","[Henry Thomas, Blake Heron, Barbara Hershey]",[Greg Marcks]

In [25]:
def collapse(L):
    L1 = []
    for i in L:
        L1.append(i.replace(" ",""))
    return L1

In [26]:
movies['cast'] = movies['cast'].apply(collapse)
movies['crew'] = movies['crew'].apply(collapse)
movies['genres'] = movies['genres'].apply(collapse)
movies['keywords'] = movies['keywords'].apply(collapse)

In [27]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [28]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [29]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [30]:
new = movies.drop(columns=['overview','genres','keywords','cast','crew'])
#new.head()

In [31]:
new['tags'] = new['tags'].apply(lambda x: " ".join(x))
new.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [32]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [33]:
vector = cv.fit_transform(new['tags']).toarray()

In [34]:
vector.shape

(4806, 5000)

In [35]:
from sklearn.metrics.pairwise import cosine_similarity

In [36]:
similarity = cosine_similarity(vector)

In [37]:
similarity

array([[1.        , 0.09107651, 0.06071767, ..., 0.02519763, 0.02817181,
        0.        ],
       [0.09107651, 1.        , 0.06451613, ..., 0.02677398, 0.        ,
        0.        ],
       [0.06071767, 0.06451613, 1.        , ..., 0.02677398, 0.        ,
        0.        ],
       ...,
       [0.02519763, 0.02677398, 0.02677398, ..., 1.        , 0.0745356 ,
        0.04774099],
       [0.02817181, 0.        , 0.        , ..., 0.0745356 , 1.        ,
        0.05337605],
       [0.        , 0.        , 0.        , ..., 0.04774099, 0.05337605,
        1.        ]])

In [38]:
new[new['title'] == 'The Lego Movie'].index[0]

np.int64(744)

In [39]:
def recommend(movie):
    index = new[new['title'] == movie].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[1:6]:
        print(new.iloc[i[0]].title)

In [40]:
recommend('Gandhi')

Gandhi, My Father
The Wind That Shakes the Barley
A Passage to India
Guiana 1838
Bloody Sunday

In [41]:
new['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [42]:
new['tags'] = new['tags'].apply(lambda x:x.lower())

In [43]:
new.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [44]:
import nltk

In [45]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [46]:
def stem(text):
    y = []
    
    for i in text.split():
        y.append(ps.stem(i))
    
    return " ".join(y)

In [47]:
new['tags'] = new['tags'].apply(stem)

In [48]:
new['tags'][0]

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

In [49]:
new['tags'][0]

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

In [50]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')

In [51]:
vectors = cv.fit_transform(new['tags']).toarray()

In [52]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [53]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0])

In [54]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      dtype=object)

In [55]:
stem('in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron')

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

In [56]:
from sklearn.metrics.pairwise import cosine_similarity

In [57]:
similarity = cosine_similarity(vectors)

In [58]:
sorted(similarity[0],reverse=True)

[np.float64(1.0),
 np.float64(0.29061909685954823),
 np.float64(0.2726248784031353),
 np.float64(0.26401000024165),
 np.float64(0.25903973506580724),
 np.float64(0.2537477434955704),
 np.float64(0.2484013136974297),
 np.float64(0.24784079854830485),
 np.float64(0.23490461932490855),
 np.float64(0.2348556961505104),
 np.float64(0.23089735286521348),
 np.float64(0.22830583024432843),
 np.float64(0.22568905807670636),
 np.float64(0.22147019900891643),
 np.float64(0.21524880100025257),
 np.float64(0.21369687880543226),
 np.float64(0.213352298825066),
 np.float64(0.2092457497388747),
 np.float64(0.20712325533373332),
 np.float64(0.20668850837512243),
 np.float64(0.2056773510573183),
 np.float64(0.2056773510573183),
 np.float64(0.20549873413169661),
 np.float64(0.20518233866439894),
 np.float64(0.20475971753873348),
 np.float64(0.20056488422556012),
 np.float64(0.20032733246124987),
 np.float64(0.20032733246124987),
 np.float64(0.199363055707225),
 np.float64(0.19510570275964212),
 np.float64(0.19391446622548786),
 np.float64(0.19344776406574832),
 np.float64(0.19344776406574832),
 np.float64(0.1926263261127128),
 np.float64(0.19184045508446734),
 np.float64(0.18983159915049982),
 np.float64(0.1898315991504998),
 np.float64(0.1894422005883515),
 np.float64(0.18857857160117855),
 np.float64(0.18641092980036),
 np.float64(0.18641092980036),
 np.float64(0.18380365552345193),
 np.float64(0.18316875326179907),
 np.float64(0.1823843010350213),
 np.float64(0.18195633571851272),
 np.float64(0.18009006755629928),
 np.float64(0.17937400083354382),
 np.float64(0.17757120130114434),
 np.float64(0.17757120130114434),
 np.float64(0.17757120130114434),
 np.float64(0.17757120130114434),
 np.float64(0.1771615786072478),
 np.float64(0.1752499093081954),
 np.float64(0.17348855898381338),
 np.float64(0.17348855898381338),
 np.float64(0.17348855898381338),
 np.float64(0.1726931567105382),
 np.float64(0.17170914210964275),
 np.float64(0.1696751579473019),
 np.float64(0.1696751579473019),
 np.float64(0.16916516233038026),
 np.float64(0.16839306718964578),
 np.float64(0.1678603981989089),
 np.float64(0.1675306779862365),
 np.float64(0.1643989873053573),
 np.float64(0.1643989873053573),
 np.float64(0.16439898730535726),
 np.float64(0.162746694241347),
 np.float64(0.16120647005479025),
 np.float64(0.16120647005479025),
 np.float64(0.1600142241187995),
 np.float64(0.15949044456578),
 np.float64(0.15819299929208316),
 np.float64(0.15719549837837185),
 np.float64(0.15608456220771372),
 np.float64(0.1559625734730109),
 np.float64(0.1559625734730109),
 np.float64(0.15404884978892908),
 np.float64(0.15220388682955233),
 np.float64(0.1522038868295523),
 np.float64(0.1522038868295523),
 np.float64(0.15042366316917008),
 np.float64(0.15042366316917008),
 np.float64(0.15007505629691606),
 np.float64(0.1487044791289829),
 np.float64(0.1487044791289829),
 np.float64(0.14856672599230308),
 np.float64(0.14797064923339878),
 np.float64(0.14763464883937316),
 np.float64(0.14763464883937316),
 np.float64(0.14763464883937316),
 np.float64(0.14704292441876157),
 np.float64(0.14704292441876157),
 np.float64(0.14704292441876154),
 np.float64(0.14615084586538157),
 np.float64(0.14615084586538157),
 np.float64(0.1454358496691159),
 np.float64(0.14543584966911588),
 np.float64(0.1453095484297741),
 np.float64(0.1453095484297741),
 np.float64(0.1438803413133505),
 np.float64(0.14349920066683505),
 np.float64(0.14349920066683505),
 np.float64(0.14309095175803563),
 np.float64(0.14309095175803563),
 np.float64(0.14309095175803563),
 np.float64(0.1430909517580356),
 np.float64(0.14237369936287486),
 np.float64(0.14165281524036175),
 np.float64(0.14097096860865022),
 np.float64(0.14097096860865022),
 np.float64(0.14059173052284343),
 np.float64(0.14019992744655632),
 np.float64(0.14019992744655632),
 np.float64(0.14019992744655632),
 np.float64(0.14019992744655632),
 np.float64(0.1389425035941821),
 np.float64(0.1389425035941821),
 np.float64(0.1389425035941821),
 np.float64(0.1389425035941821),
 np.float64(0.13812277665483924),
 np.float64(0.1371182340382122),
 np.float64(0.1371182340382122),
 np.float64(0.1371182340382122),
 np.float64(0.1371182340382122),
 np.float64(0.1371182340382122),
 np.float64(0.13699915608779772),
 np.float64(0.13678822577626598),
 np.float64(0.13657399193174952),
 np.float64(0.1354916256531435),
 np.float64(0.1354916256531435),
 np.float64(0.1354916256531435),
 np.float64(0.13513513513513514),
 np.float64(0.13513513513513514),
 np.float64(0.1342312110428049),
 np.float64(0.1342312110428049),
 np.float64(0.1342312110428049),
 np.float64(0.13334518676566626),
 np.float64(0.13300532955644181),
 np.float64(0.1316245316231641),
 np.float64(0.1316245316231641),
 np.float64(0.1316245316231641),
 np.float64(0.13151918984428584),
 np.float64(0.13151918984428584),
 np.float64(0.13151918984428584),
 np.float64(0.13151918984428584),
 np.float64(0.13065106689280268),
 np.float64(0.12996881122750908),
 np.float64(0.12996881122750908),
 np.float64(0.12996881122750908),
 np.float64(0.12996881122750908),
 np.float64(0.12996881122750908),
 np.float64(0.1289651760438322),
 np.float64(0.1289651760438322),
 np.float64(0.1283740414907742),
 np.float64(0.12734290799340264),
 np.float64(0.12734290799340264),
 np.float64(0.12683657235796025),
 np.float64(0.12683657235796025),
 np.float64(0.12683657235796025),
 np.float64(0.12683657235796025),
 np.float64(0.12655439943366653),
 np.float64(0.12655439943366653),
 np.float64(0.12655439943366653),
 np.float64(0.12629480039223434),
 np.float64(0.12535305264097507),
 np.float64(0.12527215359889848),
 np.float64(0.12427395320024),
 np.float64(0.12427395320024),
 np.float64(0.12427395320024),
 np.float64(0.12427395320023998),
 np.float64(0.12392039927415242),
 np.float64(0.12392039927415242),
 np.float64(0.12329924047901797),
 np.float64(0.12329924047901797),
 np.float64(0.12329924047901797),
 np.float64(0.12329924047901797),
 np.float64(0.12234710854292788),
 np.float64(0.1221125021745327),
 np.float64(0.1221125021745327),
 np.float64(0.1221125021745327),
 np.float64(0.1221125021745327),
 np.float64(0.1221125021745327),
 np.float64(0.1221125021745327),
 np.float64(0.12141669877745292),
 np.float64(0.12119654139092992),
 np.float64(0.12119654139092992),
 np.float64(0.1211965413909299),
 np.float64(0.1211965413909299),
 np.float64(0.12006004503753284),
 np.float64(0.12006004503753284),
 np.float64(0.12006004503753284),
 np.float64(0.12006004503753284),
 np.float64(0.11961783342433499),
 np.float64(0.11961783342433499),
 np.float64(0.11961783342433499),
 np.float64(0.11961783342433499),
 np.float64(0.11869522585912262),
 np.float64(0.1186447494690624),
 np.float64(0.1186447494690624),
 np.float64(0.1186447494690624),
 np.float64(0.1186447494690624),
 np.float64(0.11810771907149853),
 np.float64(0.11810771907149853),
 np.float64(0.11810771907149853),
 np.float64(0.11810771907149853),
 np.float64(0.11810771907149853),
 np.float64(0.1178966237837789),
 np.float64(0.11742784807525519),
 np.float64(0.11742784807525519),
 np.float64(0.11706342165578529),
 np.float64(0.1166080974034697),
 np.float64(0.1162476387438193),
 np.float64(0.11624763874381928),
 np.float64(0.11624763874381927),
 np.float64(0.11565903932254226),
 np.float64(0.11510231387903269),
 np.float64(0.11510231387903269),
 np.float64(0.11510231387903269),
 np.float64(0.1144727614064285),
 np.float64(0.1144727614064285),
 np.float64(0.1139901881468883),
 np.float64(0.11394547734377711),
 np.float64(0.11389895949029985),
 np.float64(0.11314714296070713),
 np.float64(0.11314714296070713),
 np.float64(0.11314714296070713),
 np.float64(0.11290968804428624),
 np.float64(0.11290968804428624),
 np.float64(0.11290968804428622),
 np.float64(0.11290968804428622),
 np.float64(0.11277677488692017),
 np.float64(0.11277677488692017),
 np.float64(0.11277677488692017),
 np.float64(0.11277677488692017),
 np.float64(0.11277677488692017),
 np.float64(0.11241002017619531),
 np.float64(0.11241002017619531),
 np.float64(0.11185934253567072),
 np.float64(0.11168711865749101),
 np.float64(0.11168711865749101),
 np.float64(0.11115400287534569),
 np.float64(0.11115400287534567),
 np.float64(0.11115400287534567),
 np.float64(0.11115400287534567),
 np.float64(0.11115400287534567),
 np.float64(0.11115400287534567),
 np.float64(0.11083777463036817),
 np.float64(0.11028219331407116),
 np.float64(0.11028219331407116),
 np.float64(0.11028219331407116),
 np.float64(0.11028219331407116),
 np.float64(0.11028219331407116),
 np.float64(0.11022596991336672),
 np.float64(0.10984369379093671),
 np.float64(0.1098436937909367),
 np.float64(0.1098436937909367),
 np.float64(0.1098436937909367),
 np.float64(0.10959932487023819),
 np.float64(0.10959932487023819),
 np.float64(0.10892898631973956),
 np.float64(0.10887588907733554),
 np.float64(0.10827079910776224),
 np.float64(0.10810810810810811),
 np.float64(0.10810810810810811),
 np.float64(0.10810810810810811),
 np.float64(0.10793322294408637),
 np.float64(0.10793322294408637),
 np.float64(0.10762440050012628),
 np.float64(0.10762440050012628),
 np.float64(0.10762440050012628),
 np.float64(0.10762440050012628),
 np.float64(0.10762440050012628),
 np.float64(0.10762440050012628),
 np.float64(0.10701462561817378),
 np.float64(0.10701462561817378),
 np.float64(0.10701462561817376),
 np.float64(0.106676149412533),
 np.float64(0.106676149412533),
 np.float64(0.106676149412533),
 np.float64(0.106676149412533),
 np.float64(0.106676149412533),
 np.float64(0.1061190899945022),
 np.float64(0.10529962529853128),
 np.float64(0.10529962529853128),
 np.float64(0.10529962529853128),
 np.float64(0.10529962529853128),
 np.float64(0.10529962529853128),
 np.float64(0.10529962529853128),
 np.float64(0.10529962529853128),
 np.float64(0.10524566699352861),
 np.float64(0.10524566699352861),
 np.float64(0.10514994558491725),
 np.float64(0.10514994558491725),
 np.float64(0.10514994558491725),
 np.float64(0.10514994558491725),
 np.float64(0.10514994558491725),
 np.float64(0.10514994558491725),
 np.float64(0.10514994558491723),
 np.float64(0.10514994558491723),
 np.float64(0.10439346133241542),
 np.float64(0.10397504898200727),
 np.float64(0.10397504898200727),
 np.float64(0.10397504898200727),
 np.float64(0.10397504898200727),
 np.float64(0.10397504898200727),
 np.float64(0.10397504898200727),
 np.float64(0.10397504898200727),
 np.float64(0.10356162766686666),
 np.float64(0.10283867552865913),
 np.float64(0.10283867552865913),
 np.float64(0.10283867552865913),
 np.float64(0.10283867552865913),
 np.float64(0.10274936706584831),
 np.float64(0.10269923319261937),
 np.float64(0.10269923319261937),
 np.float64(0.10269923319261937),
 np.float64(0.10195592378577323),
 np.float64(0.10195592378577323),
 np.float64(0.1019559237857732),
 np.float64(0.10146925788636821),
 np.float64(0.10146925788636821),
 np.float64(0.10146925788636821),
 np.float64(0.10146925788636821),
 np.float64(0.10146925788636821),
 np.float64(0.10146925788636821),
 np.float64(0.10067340828210367),
 np.float64(0.10067340828210367),
 np.float64(0.10067340828210367),
 np.float64(0.10067340828210367),
 np.float64(0.10067340828210367),
 np.float64(0.10067340828210367),
 np.float64(0.10067340828210367),
 np.float64(0.10067340828210367),
 np.float64(0.10067340828210367),
 np.float64(0.10067340828210367),
 np.float64(0.10067340828210367),
 np.float64(0.10067340828210367),
 np.float64(0.10067340828210367),
 np.float64(0.10042266465917388),
 np.float64(0.10042266465917388),
 np.float64(0.10028244211278005),
 np.float64(0.10028244211278005),
 np.float64(0.10028244211278005),
 np.float64(0.10028244211278005),
 np.float64(0.10028244211278005),
 np.float64(0.10028244211278005),
 np.float64(0.09968152785361249),
 np.float64(0.09913631941932194),
 np.float64(0.09913631941932194),
 np.float64(0.09913631941932194),
 np.float64(0.09913631941932194),
 np.float64(0.09913631941932194),
 np.float64(0.09913631941932194),
 np.float64(0.09913631941932194),
 np.float64(0.09913631941932194),
 np.float64(0.09863939238321438),
 np.float64(0.09863939238321438),
 np.float64(0.09863939238321438),
 np.float64(0.09863939238321438),
 np.float64(0.09863939238321438),
 np.float64(0.09863939238321438),
 np.float64(0.09863939238321438),
 np.float64(0.09863939238321438),
 np.float64(0.09863939238321438),
 np.float64(0.09863939238321438),
 np.float64(0.09802861627917438),
 np.float64(0.09802861627917438),
 np.float64(0.09695723311274393),
 np.float64(0.09695723311274393),
 np.float64(0.09695723311274393),
 np.float64(0.09695723311274393),
 np.float64(0.09687303228651607),
 np.float64(0.09687303228651607),
 np.float64(0.09672388203287416),
 np.float64(0.09672388203287416),
 np.float64(0.09672388203287416),
 np.float64(0.09672388203287416),
 np.float64(0.09592022754223367),
 np.float64(0.09592022754223367),
 np.float64(0.09491579957524991),
 np.float64(0.09491579957524991),
 np.float64(0.09491579957524991),
 np.float64(0.09491579957524991),
 np.float64(0.09491579957524991),
 np.float64(0.09491579957524991),
 np.float64(0.09491579957524991),
 np.float64(0.09491579957524991),
 np.float64(0.09491579957524991),
 np.float64(0.09491579957524991),
 np.float64(0.0949157995752499),
 np.float64(0.0949157995752499),
 np.float64(0.0949157995752499),
 np.float64(0.0949157995752499),
 np.float64(0.0949157995752499),
 np.float64(0.0949157995752499),
 np.float64(0.0949157995752499),
 np.float64(0.0949157995752499),
 np.float64(0.0949157995752499),
 np.float64(0.0949157995752499),
 np.float64(0.09394227846020416),
 np.float64(0.09394227846020416),
 np.float64(0.09394227846020416),
 np.float64(0.09394227846020416),
 np.float64(0.09394227846020416),
 np.float64(0.09394227846020416),
 np.float64(0.09394227846020416),
 np.float64(0.09394227846020416),
 np.float64(0.09367501681349609),
 np.float64(0.09367501681349609),
 np.float64(0.09320546490018),
 np.float64(0.09320546490018),
 np.float64(0.09320546490018),
 np.float64(0.09320546490018),
 np.float64(0.09320546490018),
 np.float64(0.09320546490018),
 np.float64(0.09320546490018),
 np.float64(0.09320546490018),
 np.float64(0.0930725988812425),
 np.float64(0.0930725988812425),
 np.float64(0.09299811099505542),
 np.float64(0.09248165577087425),
 np.float64(0.09248165577087424),
 np.float64(0.09208185110322616),
 np.float64(0.09208185110322616),
 np.float64(0.09208185110322616),
 np.float64(0.09208185110322616),
 np.float64(0.09208185110322616),
 np.float64(0.09208185110322616),
 np.float64(0.09158437663089954),
 np.float64(0.09158437663089954),
 np.float64(0.09158437663089952),
 np.float64(0.09158437663089952),
 np.float64(0.09158437663089952),
 np.float64(0.09158437663089952),
 np.float64(0.09158437663089952),
 np.float64(0.09158437663089952),
 np.float64(0.09158437663089952),
 np.float64(0.09119215051751065),
 np.float64(0.09119215051751065),
 np.float64(0.09119215051751065),
 np.float64(0.09119215051751065),
 np.float64(0.09119215051751065),
 np.float64(0.09119215051751065),
 np.float64(0.09119215051751065),
 np.float64(0.09119215051751065),
 np.float64(0.09097816785925636),
 np.float64(0.09032775043542898),
 np.float64(0.0902256659231352),
 np.float64(0.09004503377814962),
 np.float64(0.09004503377814962),
 np.float64(0.09004503377814962),
 np.float64(0.09004503377814962),
 np.float64(0.09004503377814962),
 np.float64(0.09004503377814962),
 np.float64(0.08968700041677191),
 np.float64(0.08948747402853657),
 np.float64(0.08948747402853657),
 np.float64(0.08948747402853657),
 np.float64(0.08948747402853657),
 np.float64(0.08948747402853657),
 np.float64(0.08948747402853657),
 np.float64(0.08948747402853657),
 np.float64(0.08948747402853657),
 np.float64(0.08867021970429453),
 np.float64(0.08867021970429453),
 np.float64(0.0886379935648677),
 np.float64(0.0885807893036239),
 np.float64(0.0885807893036239),
 np.float64(0.0885807893036239),
 np.float64(0.0885807893036239),
 np.float64(0.0885807893036239),
 np.float64(0.0885807893036239),
 np.float64(0.0885807893036239),
 np.float64(0.0885807893036239),
 np.float64(0.0885807893036239),
 np.float64(0.0885807893036239),
 np.float64(0.08787495503274936),
 np.float64(0.08787495503274936),
 np.float64(0.08787495503274936),
 np.float64(0.08787495503274936),
 np.float64(0.08787495503274936),
 np.float64(0.08787495503274936),
 np.float64(0.08787495503274936),
 np.float64(0.08787495503274936),
 np.float64(0.08787495503274936),
 np.float64(0.08718572905786445),
 np.float64(0.08718572905786445),
 np.float64(0.08718572905786445),
 np.float64(0.08718572905786445),
 np.float64(0.08718572905786445),
 np.float64(0.08718572905786445),
 np.float64(0.08718572905786445),
 np.float64(0.08710071126186844),
 np.float64(0.08710071126186844),
 np.float64(0.0863465783552691),
 np.float64(0.0863465783552691),
 np.float64(0.0863465783552691),
 np.float64(0.08585457105482137),
 np.float64(0.08585457105482137),
 np.float64(0.08585457105482137),
 np.float64(0.08585457105482137),
 np.float64(0.08585457105482137),
 np.float64(0.08585457105482137),
 np.float64(0.08585457105482136),
 np.float64(0.08561170049453902),
 np.float64(0.08561170049453902),
 np.float64(0.08561170049453902),
 np.float64(0.08561170049453902),
 np.float64(0.08489527199560176),
 np.float64(0.08489527199560176),
 np.float64(0.08489527199560176),
 np.float64(0.08489527199560176),
 np.float64(0.08489527199560176),
 np.float64(0.08489527199560176),
 np.float64(0.08489527199560176),
 np.float64(0.08489527199560176),
 np.float64(0.08458258116519013),
 np.float64(0.08458258116519013),
 np.float64(0.08458258116519013),
 np.float64(0.08458258116519013),
 np.float64(0.08458258116519013),
 np.float64(0.08458258116519013),
 np.float64(0.08458258116519013),
 np.float64(0.08433490104000933),
 np.float64(0.08419653359482289),
 np.float64(0.08419653359482289),
 np.float64(0.08419653359482289),
 np.float64(0.08351476906593233),
 np.float64(0.08336550215650926),
 np.float64(0.08336550215650926),
 np.float64(0.08336550215650926),
 np.float64(0.08336550215650926),
 np.float64(0.08336550215650926),
 np.float64(0.08336550215650926),
 np.float64(0.08336550215650926),
 np.float64(0.08336550215650926),
 np.float64(0.08336550215650926),
 np.float64(0.08336550215650926),
 np.float64(0.08336550215650926),
 np.float64(0.08336550215650926),
 np.float64(0.08284930213349333),
 np.float64(0.08284930213349333),
 np.float64(0.08284930213349333),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08219949365267865),
 np.float64(0.08108108108108109),
 np.float64(0.08108108108108109),
 np.float64(0.08108108108108109),
 np.float64(0.08108108108108109),
 np.float64(0.08108108108108109),
 np.float64(0.08108108108108109),
 np.float64(0.08108108108108109),
 np.float64(0.08108108108108109),
 np.float64(0.08108108108108109),
 np.float64(0.08108108108108109),
 np.float64(0.08108108108108109),
 np.float64(0.08108108108108109),
 np.float64(0.08099356774626426),
 np.float64(0.08094446585163528),
 np.float64(0.08094446585163528),
 np.float64(0.08094446585163528),
 np.float64(0.08094446585163528),
 np.float64(0.08094446585163528),
 np.float64(0.08094446585163528),
 np.float64(0.0803381317273391),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),

In [59]:
def recommend(movie):
    index = new[new['title'] == movie].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[1:6]:
        print(new.iloc[i[0]].title)

In [60]:
recommend('Tangled')

Out of Inferno
The Princess and the Frog
Home on the Range
Animals United
Toy Story 3

In [61]:
new.iloc[1216].title

'Autumn in New York'

In [62]:
recommend('Batman Begins')

The Dark Knight
Batman
Batman
The Dark Knight Rises
10th & Wolf

In [63]:
import pickle

In [64]:
pickle.dump(new,open("movies.pkl","wb"))

In [65]:
new["title"].values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Signed, Sealed, Delivered', 'Shanghai Calling',
       'My Date with Drew'], dtype=object)

In [66]:
pickle.dump(new.to_dict(),open("movie_dict.pkl","wb"))

In [67]:
pickle.dump(similarity,open("similarity.pkl", "wb"))